### ISSUE TITLE
iOS FirebaseAuthenticator errors

### ISSUE THREAD

**Issue by softourS** [yuv4ik/XFFirebaseAuthExample#1]
Hello @yuv4ik , I have a slight issue with the iOS IFirebaseAuthenticator. It appears that this lines:

 `AuthDataResult user = await Auth.DefaultInstance.SignInAsync (email, password);
            return await user.GetIdTokenAsync ();`

generate these errors:
**"'Auth' does not contain a definition for 'SignInAsync' and no extension method 'SignInAsync' accepting a first argument of type 'Auth' could be found"**
and
**"'AuthDataResult' does not contain a definition for 'GetIdTokenAsync' and no extension method 'GetIdTokenAsync' accepting a first argument of type 'AuthDataResult' could be found"**

I just pasted the file, well, after changing the namespace, so I'm not sure were the error truly is.

Regards

**Comment by softourS** [comment]
Never mind, I just figured out by copying the Droid code and modifying it. Just change this:

`AuthDataResult user = await Auth.DefaultInstance.SignInAsync (email, password);`
`return await user.GetIdTokenAsync ();`

for this:

`AuthDataResult user = await Auth.DefaultInstance.SignInWithPasswordAsync (email, password);`
`return await user.User.GetIdTokenAsync (false);`

and solved

Apologies for any inconvenience.

**Comment by yuv4ik** [comment]
Hello @softourS,

Glad the issue is resolved!

BR
